### ISSUE TITLE
Source Map not being generated.

### ISSUE THREAD

**Issue by Jordan4jc** [gruntjs/grunt-contrib-concat#108]
When I run my grunt task it is generating the vendor.js file but not the vendor.map file. Here are the lines from my grunt file.

```js
concat: {
	options: {
		sourceMap: true,
	},
	dev: {
		src: ['src/scripts/vendor/**/*.js'],
		dest: 'js/vendor.js'
	}
},
```

**Comment by XhmikosR** [comment]
Closing for no feedback. If the issue persists, leave a comment or CC someone to reopen it.
