### ISSUE TITLE
Normalize directory path to forward slash in sourcemap source property

### ISSUE THREAD

**Issue by liy** [gruntjs/grunt-contrib-concat#110]
Under windows, `sourcemap.js` produces: `sources:[ "..\\main.js"]`.

In this case, devtools cannot map it to the correct file. It could be the `path.relative` always returns backslash in windows.

**Comment by kirubasankars** [comment]
Yes. I having the same issue. its windows only. when I track it down. I got a temporary fix.

node_modules\grunt-contrib-concat\tasks\lib\sourcemap.js

may be line number 96 :

SourceMapConcatHelper.prototype.addlines = function(src, filename) {
    var relativeFilename = path.relative(path.dirname(this.dest), filename);

TO

SourceMapConcatHelper.prototype.addlines = function(src, filename) {
    var relativeFilename = path.relative(path.dirname(this.dest), filename).replace(/\\/g,'/');

**Comment by XhmikosR** [comment]
Duplicate of #95.
