### ISSUE TITLE
Change Default Seperator to `;\n`

### ISSUE THREAD

**Issue by regnerus** [gruntjs/grunt-contrib-concat#120]
In the example configuration the default separator is listed as `separator: ';'` this sometimes leads to issues could this be changed to `separator: ';\n'`.

**Comment by schmod** [comment]
The default separator is [`grunt.util.linefeed`](http://gruntjs.com/api/grunt.util#grunt.util.linefeed), not `';'`.  

That being said, `;\n` is indeed a safer example to give for JavaScript, because you could accidentally end up concatenating live code into a `//` comment.

**Comment by arthurvr** [comment]
I opened a PR for this. See #122

**Comment by schmod** [comment]
Looks good. Thanks!
