### ISSUE TITLE
Concat same file multiple times

### ISSUE THREAD

**Issue by pixevil** [gruntjs/grunt-contrib-concat#124]
I'd like to use grunt-contrib-concat for application frontend HTML templating purposes and this would be useful for me.

I'd like to define page partials and and concatenate them inside an output file that is going to be compiled by handlebars.

I've got everything set up, however Concat doesn't allow me to use the same file more than once.

Basically concat is filtering the sources so they don't occur more than once. The second partial1.hbs will not be concatenated. Is there any way to do this?

```javascript
pageconcat: {
    src: [
       'app/templates/partial1.hbs',
       'app/templates/partial2.hbs',
       'app/templates/partial1.hbs'
    ],
    dest: 'app/result.hbs'
}
```

**Comment by sindresorhus** [comment]
Nope, it's grunt that deduplicates, not this plugin.

**Comment by romuleald** [comment]
@sindresorhus can you explain more?
