### ISSUE TITLE
Files matched with glob pattern end with wrong order in the concatenated file

### ISSUE THREAD

**Issue by diosney** [gruntjs/grunt-contrib-concat#126]
As title says.

For further information please, look at:

http://stackoverflow.com/questions/30402972/grunt-concat-angularjs

**Comment by diosney** [comment]
https://github.com/gruntjs/grunt/issues/1338

**Comment by gruberb** [comment]
Maybe this issue is similar:

http://stackoverflow.com/questions/30888486/angular-state-already-defined-error-after-running-concat-uglify

**Comment by diosney** [comment]
@gruberb Yes, it is the same issue but the final solution should be found in grunt core itself and not in Angular nor in the contrib-concat libraries.

I will close this issue since I already opened a discussion at the grunt-core repo.

https://github.com/gruntjs/grunt/issues/1338

It seems that a possible solution to this could be to let specify grunt users  in the tasks options object the algorithm to organize file paths.
