### ISSUE TITLE
Multiline suppor

### ISSUE THREAD

**Issue by zxxc** [gruntjs/grunt-contrib-concat#132]
Needed multiline support, like this:
```javascript
  <!-- include: "type": "js",
                      "files": "modules/*/*.js,
                                  modules/**/*.js, 
                                  !**/tests/*.js" -->
```

**Comment by jrcryer** [comment]
Hi @zxxc, can you post your Gruntfile? Not sure where the `<!-- include: -->` is coming from?

**Comment by zxxc** [comment]
Now I'm thinking that I was trying to post to another plugin, sorry for wasting your time
