### ISSUE TITLE
Exclude not working

### ISSUE THREAD

**Issue by zxxc** [gruntjs/grunt-contrib-concat#133]
I've tryed Needed multiline support, like this:
  

I expect that files like modules/core.js will be at first positions
then will be all other js files, except files in "tests" directory
but files from "tests" also included,
Unexpected result:
  ```javascript
  <script src="modules/core/core.js"></script>
  <script src="modules/core/config/routes.js"></script>
  <script src="modules/core/controllers/home.js"></script>
  <script src="modules/core/services/test-service.js"></script>
  <script src="modules/core/tests/e2e/home/home.po.js"></script>
  <script src="modules/core/tests/e2e/home/home.spec.js"></script>
  <script src="modules/core/tests/unit/home.spec.js"></script>
```

**Comment by jrcryer** [comment]
Hi @zxxc, what are you trying to achieve here? This plugin isn't designed to replace HTML content with the output file.  Maybe you should take a look at [grunt-usemin](https://github.com/yeoman/grunt-usemin) which can be used with this plugin.

**Comment by zxxc** [comment]
Now I'm thinking that I was trying to post to another plugin, sorry for wasting your time

**Comment by jrcryer** [comment]
@zxxc no problem - glad to be of help!
