### ISSUE TITLE
Bug when using "expand: true"

### ISSUE THREAD

**Issue by JasonKid** [gruntjs/grunt-contrib-concat#135]
When I write this code:
```javascript
files: [{
    expand: true,
    cwd: 'css/src',
    src: ['*.css', '!home.css'],
    dest: 'css/src/home.css'
 }]
```
It generates a folder names "home.css" which contains every copy of files in css/src.

But it works when I write:
```javascript
files: [{
    src: ['css/src/*.css', '!css/src/<%= pkg.name %>.css'],
    dest: 'css/src/index.css'
}]
```

**Comment by jrcryer** [comment]
Hi @JasonKid,

I think you've confused the `dest` property in your first example.  If you read the docs (http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically), you'll see this is the destination folder and not  the file.  I think you've come to the best solution with your second solution.

Ta

**Comment by shama** [comment]
@jrcryer Is correct, thanks!
