### ISSUE TITLE
Сomments in the middle

### ISSUE THREAD

**Issue by asokol1981** [gruntjs/grunt-contrib-concat#143]
Comments are not stripped in the middle, just at the beginning of the file.

**Comment by shama** [comment]
Could you provide more information to what you are trying and what you expected?

If you're using `stripBanners` that is the intended behavior. If you're looking to remove comments you may want to use a task geared for that, such as uglify or a comment stripping lib such as https://github.com/shama/uncommentify

**Comment by asokol1981** [comment]
Thank you for answer. I'll look uncommentify.
