### ISSUE TITLE
Upgrade Chalk

### ISSUE THREAD

**Issue by bxyoung89** [gruntjs/grunt-contrib-concat#189]
The version of chalk that this repo is using is `1.1.1`. That is requiring `ansi-styles@2.2.0`. However, that version got unlisted. Please update to the latest so that I don't have to mess around with package.lock. 

Thanks!

**Comment by vladikoff** [comment]
@bxyoung89 we use ` "chalk": "^1.0.0",`, which picks up 1.1.3 these days, you should update your lock file, reinstall or something.
