### ISSUE TITLE
Concat in specific order

### ISSUE THREAD

**Issue by ghost** [gruntjs/grunt-contrib-concat#23]
how can I concatenate the files in a specific order?

I'm using regexp to concatenate multiple files but I need one of them to be at the end.

Brunch.io has something like this:

``` files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        ...
      order:
        before: [
           ...
        ]
        after: [
          ...
        ]
```

Thanks

**Comment by amitzur** [comment]
Sorry, but this doesn't work from grunt version 0.4.1 (not sure about versions below)
Need to exclude after.js explicitly, then include it, like described in the docs:
http://gruntjs.com/configuring-tasks

// All files in alpha order, but with bar.js at the end.
{src: ['foo/*.js', '!foo/bar.js', 'foo/bar.js'], dest: ...}

**Comment by utdrmac** [comment]
This is still an issue in 1.0.1
