### ISSUE TITLE
It seems like filepath  is not correct when work with cwd option.

### ISSUE THREAD

**Issue by 2betop** [gruntjs/grunt-contrib-concat#31]
The correct value of filepath should be f.cwd + filepath.

var src = banner + f.src.filter(function(filepath) {
        // Warn on and remove invalid source files (if nonull was set).
        if (!grunt.file.exists(filepath)) {
          grunt.log.warn('Source file "' + filepath + '" not found.');
          return false;
        } else {
          return true;
        }
      })

**Comment by jahooma** [comment]
bilalq's solution worked for me, but I also needed to add `flatten: true` since my files were in multiple directories. 
Let me just add my vote that something is not quite right here and probably should be fixed.

**Comment by erethnor** [comment]
This got me as well.
I agree with the comments above, this doesn't seem to be the most expected behaviour.

**Comment by Lutreer** [comment]
how to use

**Comment by christw92** [comment]
@bilalq so something like this should work:
concat: {
  someTarget: {
    rename: function(dest) { return dest },
    expand: true,
    cwd: 'tmp',
    src: ['file1','file2'],
    dest: 'concat.js'
  }
}

leading to the files in ./tmp/file1 and ./tmp/file2 being concatenated and saved ./concat.js ?

Because this config is not giving me any errors/warnings but ./concat.js is not created.
