### ISSUE TITLE
Abort when files missing

### ISSUE THREAD

**Issue by FrankFang** [gruntjs/grunt-contrib-concat#58]
How can I have Grunt abort when some file is missing in a concat task?
You use `grunt.log.warn` to warn, why not use `grunt.warn`? 
Maybe provide an `strict` option or something.

**Comment by SimonKenyonShepard** [comment]
Did this ever get implemented in the Grunt core? A year later and our project is still suffering the same, would love to be able to turn on the ability to fail when a specified file is missing.

**Comment by FrankFang** [comment]
@SimonKenyonShepard  I turned into gulp several months ago. Have a try.

**Comment by vladimirkosmala** [comment]
This topic is still relevant. grunt-contrib-concat should have an option to abort when file missing when we use it in production.
