### ISSUE TITLE
adding basedir option

### ISSUE THREAD

**Issue by salvador-dali** [gruntjs/grunt-contrib-concat#81]
Is it possible to add a basedir option which will do something like this

`src: [
       'public/js/libs/file1.min.js',
       'public/js/libs/file2.min.js',
       'public/js/libs/file3.min.js',
       'public/js/libs/file4.min.js'
]`

instead of carying around all this public/js/libs/ to put it inside basedir and specify only file1.min.js, ... file4.min.js  in src.

**Comment by zzzhan** [comment]
It is not work. The config can copy the files, but can not concat.
