### ISSUE TITLE
Invalid line in sourcemaps

### ISSUE THREAD

**Issue by Toilal** [gruntjs/grunt-contrib-concat#94]
I use grunt-contrib-concat and have an issue with debugging through sourcemaps using firefox and intellij IDEA. It works properly with Chrome though.

I have made some tests with grunt-contrib-concat using npm shrinkwrap to force source-map dependency version.

It works with grunt-contrib-concat, using source-map 0.1.32. Then, with any later source-map release, sourcemap are recognized, but a bit buggy with some tools. They works with chrome, but not with firefox nor intellij idea. Lines mapping seems to have an additionnal offset and setting breakpoints on sources will break at invalid lines, 1 or 2 lines after set breakpoint ...

see also https://github.com/mozilla/source-map/issues/132 and https://github.com/mishoo/UglifyJS2/issues/492

**Comment by XhmikosR** [comment]
This should be already fixed in https://github.com/gruntjs/grunt-contrib-concat/pull/103
