### ISSUE TITLE
options.filter is not used

### ISSUE THREAD

**Issue by akhoury** [gruntjs/grunt-contrib-concat#98]
It doesn't look like the `options.filter` is currently used, is that by design? 
I understand the implication of using some __fs.stats__  methods, such as `isDirectory `, because that wouldn't really make sense, but what about the option of passing a filter function? 

> `filter` Either a valid [fs.Stats method name](http://nodejs.org/docs/latest/api/fs.html#fs_class_fs_stats) or a function that is passed the matched `src` filepath and returns `true` or `false`.

source: http://gruntjs.com/configuring-tasks

__EDIT__: I should probably add that 
```javascript
module.exports = function(grunt) {
    var myFilter = function(srcPath) {
        console.log('Filtering: >>>>', srcPath); 
        return true; 
    };
    
    grunt.initConfig({
        concat: {
            options: {
                filter: myFilter,
                separator: '\n///I separate\n',
                expand: false, // or true, doesn't matter
                cwd: '.' // or undefined, doesn't matter
            },
            dist: {
                src: ['src/1.js', 'src/2.js', 'src/3.js'],
                dest: 'dist/all.js'
            }
        }
    });
    grunt.loadNpmTasks("grunt-contrib-concat");
    grunt.registerTask("default", ["concat"]);
};
```

does not execute the filter function.

**Comment by shama** [comment]
`filter` isn't a task option but part of the src/dest block of the Grunt config:

```js
concat: {
  options: {
  },
  src: ['foo.js'],
  dest: 'baz.js',
  // Filter belongs to Grunt so it goes here
  filter: function () {}
}
```
