### ISSUE TITLE
Order Problems: First -> Wildcard -> Last

### ISSUE THREAD

**Issue by graygilmore** [gruntjs/grunt-contrib-concat#99]
I want to concat files in this order:

```
first.file
**/*.file
last.file
```

Unfortunately, the file it creates looks like:

```
first.file
**/*.file
```

Where `last.file` is included in the wildcard.

**Comment by errorstack** [comment]
but, what if first.file is in **/*.file?

**Comment by DominikDitoIvosevic** [comment]
@graygilmore Could you write your Gruntfile with this setup?
